### ISSUE TITLE
Can't use it(

### ISSUE THREAD

**Issue by Pocker88** [BukuBukuChagma/Google-ReCaptcha-V2-Solver#1]
I didn't understand how it use.. I never work before with python.. I use Tampermonkey extension on Google Chrome PC. Sorry Sir :( thank you so much for your sharing work!!

**Comment by BukuBukuChagma** [comment]
> I didn't understand how it use.. I never work before with python.. I use Tampermonkey extension on Google Chrome PC. Sorry Sir :( thank you so much for your sharing work!!

@Pocker88 ah thats sad. I'm an AI student so python is my main language. I'll see if I can turn this into a browser extension using javascript.

**Comment by Pocker88** [comment]
@BukuBukuChagma That will be amazing if you can do it. Thank you so much Sir!!! Awesome
